### ISSUE TITLE
Where is the store

### ISSUE THREAD

**Issue by rodryquintero** [jcouyang/transdux#11]
Sorry for the potentially dumb question, but how do I implement the store. Is it just a plain object we import on every module?

The documentartion needs some examples illustrating about this topic.

**Comment by jcouyang** [comment]
sorry for the lack of documentation, store is actually in channels which you don't really need to care about, it's all take care by transdux. the only thing you need to do is to create actions and bind them to transdux

**Comment by rodryquintero** [comment]
Thanks for the quick reply. I am now trying to get my head around this bit.

```this.dispatch(MainSection, 'complete',{id:todo.id})}``

Why do I need to pass the `MainSection` component when I am dispatching actions?

**Comment by jcouyang** [comment]
because transdux need to know which channel you send message to, in this case, it means send a message to MainSection

**Comment by rodryquintero** [comment]
Got it... thanks for the quick reply.
